@extends ('layouts/master')
@section ('content')
    
    @include('components/header')
    @include('partials/service')
    @include('components/contact')
    @include('partials/about')
    @include('components/letsgo')
    @include('partials/project')
    @include('components/modal')
    @include('components/videoSection')
    @include('partials/team')
    @include('partials/price')
    @include('partials/pageSection')
    @include('partials/slider')
    @include('components/contactTwo')
    @include('partials/blog')
    @include('components/footer')
@endsection